//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer211 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer211);
    
    MainRibbon = new wxRibbonBar(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxRIBBON_BAR_SHOW_PAGE_LABELS);
    MainRibbon->SetArtProvider(new wxRibbonDefaultArtProvider);
    
    boxSizer211->Add(MainRibbon, 0, wxEXPAND, WXC_FROM_DIP(5));
    MainRibbon->Realize();
    wxBoxSizer* boxSizer544 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer211->Add(boxSizer544, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    LeftPanel0 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    LeftPanel0->SetBackgroundColour(wxColour(wxT("rgb(235,235,235)")));
    wxFont LeftPanel0Font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
    LeftPanel0Font.SetWeight(wxFONTWEIGHT_BOLD);
    LeftPanel0->SetFont(LeftPanel0Font);
    
    boxSizer544->Add(LeftPanel0, 0, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer594 = new wxBoxSizer(wxVERTICAL);
    LeftPanel0->SetSizer(boxSizer594);
    
    m_panel598 = new wxPanel(LeftPanel0, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(LeftPanel0, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_panel598->SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHT));
    
    boxSizer594->Add(m_panel598, 0, wxRIGHT|wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer600 = new wxBoxSizer(wxVERTICAL);
    m_panel598->SetSizer(boxSizer600);
    
    m_staticText602 = new wxStaticText(m_panel598, wxID_ANY, _("Tight-Binding Model Attributes"), wxDefaultPosition, wxDLG_UNIT(m_panel598, wxSize(-1,-1)), 0);
    m_staticText602->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHTTEXT));
    
    boxSizer600->Add(m_staticText602, 0, wxALL, WXC_FROM_DIP(5));
    
    LeftPanel = new wxNotebook(LeftPanel0, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(LeftPanel0, wxSize(-1,-1)), wxBK_DEFAULT);
    LeftPanel->SetName(wxT("LeftPanel"));
    
    boxSizer594->Add(LeftPanel, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    mainpanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxFULL_REPAINT_ON_RESIZE|wxTAB_TRAVERSAL);
    mainpanel->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    boxSizer544->Add(mainpanel, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(LeftPanel)){
        wxPersistenceManager::Get().RegisterAndRestore(LeftPanel);
    } else {
        wxPersistenceManager::Get().Restore(LeftPanel);
    }
    #endif
    
    SetName(wxT("MainFrameBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(800,500)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_SIZE, wxSizeEventHandler(MainFrameBaseClass::MainFrameBaseClass_Resize), NULL, this);
    this->Connect(wxEVT_MOVE, wxMoveEventHandler(MainFrameBaseClass::MainFrameBaseClass_Move), NULL, this);
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(MainFrameBaseClass::MainFrameClose), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(wxEVT_SIZE, wxSizeEventHandler(MainFrameBaseClass::MainFrameBaseClass_Resize), NULL, this);
    this->Disconnect(wxEVT_MOVE, wxMoveEventHandler(MainFrameBaseClass::MainFrameBaseClass_Move), NULL, this);
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(MainFrameBaseClass::MainFrameClose), NULL, this);
    
}

GraphBaseClass::GraphBaseClass(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer215 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer215);
    
    TopPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(300,-1)), wxTAB_TRAVERSAL);
    TopPanel->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    boxSizer215->Add(TopPanel, 0, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer241 = new wxBoxSizer(wxHORIZONTAL);
    TopPanel->SetSizer(boxSizer241);
    
    SetName(wxT("GraphBaseClass"));
    SetMinClientSize(wxSize(400,300));
    SetSize(wxDLG_UNIT(this, wxSize(400,300)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
}

GraphBaseClass::~GraphBaseClass()
{
}

GridBaseClass::GridBaseClass(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    SetName(wxT("GridBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(400,300)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
}

GridBaseClass::~GridBaseClass()
{
}

ColorsBaseClass::ColorsBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    this->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    SetName(wxT("ColorsBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(ColorsBaseClass::OnClose), NULL, this);
    
}

ColorsBaseClass::~ColorsBaseClass()
{
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(ColorsBaseClass::OnClose), NULL, this);
    
}

WelcomeClassBase::WelcomeClassBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    this->SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    this->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_BACKGROUND));
    
    m_timer1089 = new wxTimer;
    m_timer1089->Start(1000, false);
    
    SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_BACKGROUND));
    SetName(wxT("WelcomeClassBase"));
    SetMinClientSize(wxSize(200,120));
    SetSize(wxDLG_UNIT(this, wxSize(200,120)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_timer1089->Connect(wxEVT_TIMER, wxTimerEventHandler(WelcomeClassBase::OnTick), NULL, this);
    
}

WelcomeClassBase::~WelcomeClassBase()
{
    m_timer1089->Disconnect(wxEVT_TIMER, wxTimerEventHandler(WelcomeClassBase::OnTick), NULL, this);
    
    m_timer1089->Stop();
    wxDELETE( m_timer1089 );

}

UpdateClassBase::UpdateClassBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer1098 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1098);
    
    welcomeImage = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(this, wxSize(650,285)), 0 );
    
    boxSizer1098->Add(welcomeImage, 0, wxALL, WXC_FROM_DIP(5));
    welcomeImage->SetMinSize(wxSize(650,285));
    
    m_hyperLink1104 = new wxHyperlinkCtrl(this, wxID_ANY, _("Check for TBStudio updates"), wxT("https://tight-binding.com"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxHL_DEFAULT_STYLE);
    m_hyperLink1104->SetNormalColour(wxColour(wxT("#0000FF")));
    m_hyperLink1104->SetHoverColour(wxColour(wxT("#0000FF")));
    m_hyperLink1104->SetVisitedColour(wxColour(wxT("#FF0000")));
    
    boxSizer1098->Add(m_hyperLink1104, 0, wxALL, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer1118 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer1098->Add(boxSizer1118, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer1120 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer1118->Add(boxSizer1120, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    asdw = new wxStaticText(this, wxID_ANY, _("Serial Number:"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer1120->Add(asdw, 0, wxLEFT|wxRIGHT|wxTOP, WXC_FROM_DIP(5));
    
    SNTextBox = new wxRichTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,110)), wxTE_MULTILINE|wxTE_PROCESS_TAB|wxTE_PROCESS_ENTER|wxWANTS_CHARS);
    
    boxSizer1120->Add(SNTextBox, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    SNTextBox->SetMinSize(wxSize(-1,110));
    
    m_button1124 = new wxButton(this, wxID_ANY, _("Copy to Clipboard"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer1120->Add(m_button1124, 0, wxALL, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer1122 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer1118->Add(boxSizer1122, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText1110 = new wxStaticText(this, wxID_ANY, _("Activation key:"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer1122->Add(m_staticText1110, 0, wxLEFT|wxRIGHT|wxTOP, WXC_FROM_DIP(5));
    
    AKTextBox = new wxRichTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,110)), wxTE_MULTILINE|wxTE_PROCESS_TAB|wxTE_PROCESS_ENTER|wxWANTS_CHARS);
    
    boxSizer1122->Add(AKTextBox, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    AKTextBox->SetMinSize(wxSize(-1,110));
    
    m_button1114 = new wxButton(this, wxID_ANY, _("Activate"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer1122->Add(m_button1114, 0, wxALL|wxALIGN_RIGHT, WXC_FROM_DIP(5));
    
    SetName(wxT("UpdateClassBase"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    welcomeImage->Connect(wxEVT_LEFT_DOWN, wxMouseEventHandler(UpdateClassBase::ImageOnMouseLeftDown), NULL, this);
    welcomeImage->Connect(wxEVT_LEFT_UP, wxMouseEventHandler(UpdateClassBase::ImageOnMouseLeftUp), NULL, this);
    welcomeImage->Connect(wxEVT_MOVE, wxMoveEventHandler(UpdateClassBase::ImageOnMouseMove), NULL, this);
    m_button1124->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(UpdateClassBase::CopyClipboardOnClick), NULL, this);
    m_button1114->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(UpdateClassBase::ActivateOnClick), NULL, this);
    
}

UpdateClassBase::~UpdateClassBase()
{
    welcomeImage->Disconnect(wxEVT_LEFT_DOWN, wxMouseEventHandler(UpdateClassBase::ImageOnMouseLeftDown), NULL, this);
    welcomeImage->Disconnect(wxEVT_LEFT_UP, wxMouseEventHandler(UpdateClassBase::ImageOnMouseLeftUp), NULL, this);
    welcomeImage->Disconnect(wxEVT_MOVE, wxMoveEventHandler(UpdateClassBase::ImageOnMouseMove), NULL, this);
    m_button1124->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(UpdateClassBase::CopyClipboardOnClick), NULL, this);
    m_button1114->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(UpdateClassBase::ActivateOnClick), NULL, this);
    
}
