//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _PECSJUNC_GUI_WXCRAFTER_BASE_CLASSES_H
#define _PECSJUNC_GUI_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/art.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/notebook.h>
#include <wx/dialog.h>
#include <wx/statbmp.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBaseClass : public wxFrame
{
protected:
    wxRibbonBar* MainRibbon;
    wxPanel* LeftPanel0;
    wxPanel* m_panel598;
    wxStaticText* m_staticText602;
    wxNotebook* LeftPanel;
    wxPanel* mainpanel;

protected:
    virtual void MainFrameBaseClass_Resize(wxSizeEvent& event) { event.Skip(); }
    virtual void MainFrameBaseClass_Move(wxMoveEvent& event) { event.Skip(); }

public:
    wxRibbonBar* GetMainRibbon() { return MainRibbon; }
    wxStaticText* GetStaticText602() { return m_staticText602; }
    wxPanel* GetPanel598() { return m_panel598; }
    wxNotebook* GetLeftPanel() { return LeftPanel; }
    wxPanel* GetLeftPanel0() { return LeftPanel0; }
    wxPanel* GetMainpanel() { return mainpanel; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,500), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX|wxFULL_REPAINT_ON_RESIZE);
    virtual ~MainFrameBaseClass();
};


class GraphBaseClass : public wxPanel
{
protected:
    wxPanel* TopPanel;

protected:

public:
    wxPanel* GetTopPanel() { return TopPanel; }
    GraphBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,300), long style = wxTAB_TRAVERSAL);
    virtual ~GraphBaseClass();
};


class GridBaseClass : public wxPanel
{
protected:

protected:

public:
    GridBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,300), long style = wxTAB_TRAVERSAL);
    virtual ~GridBaseClass();
};


class ColorsBaseClass : public wxDialog
{
protected:

protected:
    virtual void OnClose(wxCloseEvent& event) { event.Skip(); }

public:
    ColorsBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Colors"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxSTAY_ON_TOP|wxCLOSE_BOX|wxBORDER_STATIC);
    virtual ~ColorsBaseClass();
};


class WelcomeClassBase : public wxDialog
{
protected:
    wxStaticBitmap* welcomeimage;
    wxTimer* m_timer1089;

protected:
    virtual void OnTick(wxTimerEvent& event) { event.Skip(); }

public:
    wxStaticBitmap* GetWelcomeimage() { return welcomeimage; }
    wxTimer* GetTimer1089() { return m_timer1089; }
    WelcomeClassBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT(""), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(650,325), long style = wxSTAY_ON_TOP|wxBORDER_SIMPLE);
    virtual ~WelcomeClassBase();
};

#endif
