//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer211 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer211);
    
    MainRibbon = new wxRibbonBar(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxRIBBON_BAR_SHOW_PAGE_LABELS);
    MainRibbon->SetArtProvider(new wxRibbonDefaultArtProvider);
    
    boxSizer211->Add(MainRibbon, 0, wxEXPAND, WXC_FROM_DIP(5));
    
    m_ribbonPage340 = new wxRibbonPage(MainRibbon, wxID_ANY, _("File"), wxNullBitmap, 0);
    MainRibbon->SetActivePage( m_ribbonPage340 );
    
    m_ribbonPanel981 = new wxRibbonPanel(m_ribbonPage340, wxID_ANY, _("My Label"), wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(m_ribbonPage340, wxSize(-1,-1)), wxRIBBON_PANEL_DEFAULT_STYLE);
    
    m_ribbonButtonBar983 = new wxRibbonButtonBar(m_ribbonPanel981, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_ribbonPanel981, wxSize(-1,-1)), 0);
    
    m_ribbonButtonBar983->AddButton(wxID_OPEN, _("Open"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar983->AddButton(wxID_SAVE, _("Save"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    m_ribbonButtonBar983->Realize();
    
    m_ribbonPage462 = new wxRibbonPage(MainRibbon, wxID_ANY, _("Edit"), wxNullBitmap, 0);
    MainRibbon->SetActivePage( m_ribbonPage462 );
    
    m_ribbonPanel1043 = new wxRibbonPanel(m_ribbonPage462, wxID_ANY, _("My Label"), wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(m_ribbonPage462, wxSize(-1,-1)), wxRIBBON_PANEL_DEFAULT_STYLE);
    
    m_ribbonButtonBar1045 = new wxRibbonButtonBar(m_ribbonPanel1043, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_ribbonPanel1043, wxSize(-1,-1)), 0);
    
    m_ribbonButtonBar1045->AddButton(wxID_REFRESH, _("Structure Style"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    m_ribbonButtonBar1045->Realize();
    
    m_ribbonPage606 = new wxRibbonPage(MainRibbon, wxID_ANY, _("View"), wxNullBitmap, 0);
    MainRibbon->SetActivePage( m_ribbonPage606 );
    
    m_ribbonPanel608 = new wxRibbonPanel(m_ribbonPage606, wxID_ANY, _("My Label"), wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(m_ribbonPage606, wxSize(-1,-1)), wxRIBBON_PANEL_DEFAULT_STYLE);
    
    m_ribbonButtonBar610 = new wxRibbonButtonBar(m_ribbonPanel608, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_ribbonPanel608, wxSize(-1,-1)), 0);
    
    m_ribbonButtonBar610->AddButton(wxID_APPLY, _("Start Page"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar610->AddButton(wxID_ADD, _("Terminal"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar610->AddButton(wxID_BACKWARD, _("Data Grid"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    m_ribbonButtonBar610->Realize();
    
    m_ribbonPage548 = new wxRibbonPage(MainRibbon, wxID_ANY, _("Methods"), wxNullBitmap, 0);
    m_ribbonPage548->Hide();
    MainRibbon->SetActivePage( m_ribbonPage548 );
    
    m_ribbonPanel550 = new wxRibbonPanel(m_ribbonPage548, wxID_ANY, _("Voltametry"), wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(m_ribbonPage548, wxSize(-1,-1)), wxRIBBON_PANEL_DEFAULT_STYLE);
    
    m_ribbonButtonBar582 = new wxRibbonButtonBar(m_ribbonPanel550, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_ribbonPanel550, wxSize(-1,-1)), 0);
    
    m_ribbonButtonBar582->AddButton(wxID_ANY, _("Button"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar582->AddButton(wxID_ANY, _("Button"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar582->AddButton(wxID_ANY, _("Button"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    m_ribbonButtonBar582->Realize();
    
    m_ribbonPage464 = new wxRibbonPage(MainRibbon, wxID_ANY, _("Analyze Data"), wxNullBitmap, 0);
    m_ribbonPage464->Hide();
    MainRibbon->SetActivePage( m_ribbonPage464 );
    
    m_ribbonPanel522 = new wxRibbonPanel(m_ribbonPage464, wxID_ANY, _("Panel1"), wxNullBitmap, wxDefaultPosition, wxDLG_UNIT(m_ribbonPage464, wxSize(-1,-1)), wxRIBBON_PANEL_DEFAULT_STYLE);
    
    m_ribbonButtonBar528 = new wxRibbonButtonBar(m_ribbonPanel522, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_ribbonPanel522, wxSize(-1,-1)), 0);
    
    m_ribbonButtonBar528->AddButton(wxID_EXECUTE, _("2D"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar528->AddButton(wxID_COPY, _("3D"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar528->AddButton(wxID_DUPLICATE, _("Glut"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar528->AddButton(wxID_IGNORE, _("mgl1"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_NORMAL);
    
    m_ribbonButtonBar528->AddButton(wxID_ANY, _("Button"), wxXmlResource::Get()->LoadBitmap(wxT("placeholder")), _("Help String"), wxRIBBON_BUTTON_HYBRID);
    m_ribbonButtonBar528->Realize();
    MainRibbon->Realize();
    wxBoxSizer* boxSizer544 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer211->Add(boxSizer544, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    LeftPanel0 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    LeftPanel0->SetBackgroundColour(wxColour(wxT("rgb(235,235,235)")));
    wxFont LeftPanel0Font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
    LeftPanel0Font.SetWeight(wxFONTWEIGHT_BOLD);
    LeftPanel0->SetFont(LeftPanel0Font);
    
    boxSizer544->Add(LeftPanel0, 0, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer594 = new wxBoxSizer(wxVERTICAL);
    LeftPanel0->SetSizer(boxSizer594);
    
    m_panel598 = new wxPanel(LeftPanel0, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(LeftPanel0, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_panel598->SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHT));
    
    boxSizer594->Add(m_panel598, 0, wxRIGHT|wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer600 = new wxBoxSizer(wxVERTICAL);
    m_panel598->SetSizer(boxSizer600);
    
    m_staticText602 = new wxStaticText(m_panel598, wxID_ANY, _("Tight-Binding Model Attributes"), wxDefaultPosition, wxDLG_UNIT(m_panel598, wxSize(-1,-1)), 0);
    m_staticText602->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHTTEXT));
    
    boxSizer600->Add(m_staticText602, 0, wxALL, WXC_FROM_DIP(5));
    
    LeftPanel = new wxNotebook(LeftPanel0, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(LeftPanel0, wxSize(-1,-1)), wxBK_DEFAULT);
    LeftPanel->SetName(wxT("LeftPanel"));
    
    boxSizer594->Add(LeftPanel, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    mainpanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxFULL_REPAINT_ON_RESIZE|wxTAB_TRAVERSAL);
    mainpanel->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    boxSizer544->Add(mainpanel, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(LeftPanel)){
        wxPersistenceManager::Get().RegisterAndRestore(LeftPanel);
    } else {
        wxPersistenceManager::Get().Restore(LeftPanel);
    }
    #endif
    
    SetName(wxT("MainFrameBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(800,500)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_SIZE, wxSizeEventHandler(MainFrameBaseClass::MainFrameBaseClass_Resize), NULL, this);
    this->Connect(wxEVT_MOVE, wxMoveEventHandler(MainFrameBaseClass::MainFrameBaseClass_Move), NULL, this);
    m_ribbonButtonBar983->Connect(wxID_OPEN, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnOpen_OnClick), NULL, this);
    m_ribbonButtonBar983->Connect(wxID_SAVE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnSave_OnClick), NULL, this);
    m_ribbonButtonBar1045->Connect(wxID_REFRESH, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnStructureStyle_OnClick), NULL, this);
    m_ribbonButtonBar610->Connect(wxID_APPLY, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnMain_OnClick), NULL, this);
    m_ribbonButtonBar610->Connect(wxID_ADD, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnTerminal_OnClick), NULL, this);
    m_ribbonButtonBar610->Connect(wxID_BACKWARD, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnGrid_OnClick), NULL, this);
    m_ribbonButtonBar528->Connect(wxID_EXECUTE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::B2D), NULL, this);
    m_ribbonButtonBar528->Connect(wxID_COPY, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::Btn3D_OnClick), NULL, this);
    m_ribbonButtonBar528->Connect(wxID_DUPLICATE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::B3D), NULL, this);
    m_ribbonButtonBar528->Connect(wxID_IGNORE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::mgl_test), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(wxEVT_SIZE, wxSizeEventHandler(MainFrameBaseClass::MainFrameBaseClass_Resize), NULL, this);
    this->Disconnect(wxEVT_MOVE, wxMoveEventHandler(MainFrameBaseClass::MainFrameBaseClass_Move), NULL, this);
    m_ribbonButtonBar983->Disconnect(wxID_OPEN, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnOpen_OnClick), NULL, this);
    m_ribbonButtonBar983->Disconnect(wxID_SAVE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnSave_OnClick), NULL, this);
    m_ribbonButtonBar1045->Disconnect(wxID_REFRESH, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnStructureStyle_OnClick), NULL, this);
    m_ribbonButtonBar610->Disconnect(wxID_APPLY, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnMain_OnClick), NULL, this);
    m_ribbonButtonBar610->Disconnect(wxID_ADD, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnTerminal_OnClick), NULL, this);
    m_ribbonButtonBar610->Disconnect(wxID_BACKWARD, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::BtnGrid_OnClick), NULL, this);
    m_ribbonButtonBar528->Disconnect(wxID_EXECUTE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::B2D), NULL, this);
    m_ribbonButtonBar528->Disconnect(wxID_COPY, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::Btn3D_OnClick), NULL, this);
    m_ribbonButtonBar528->Disconnect(wxID_DUPLICATE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::B3D), NULL, this);
    m_ribbonButtonBar528->Disconnect(wxID_IGNORE, wxEVT_COMMAND_RIBBONBUTTON_CLICKED, wxRibbonButtonBarEventHandler(MainFrameBaseClass::mgl_test), NULL, this);
    
}

GraphBaseClass::GraphBaseClass(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer215 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer215);
    
    TopPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(300,-1)), wxTAB_TRAVERSAL);
    TopPanel->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    boxSizer215->Add(TopPanel, 0, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer241 = new wxBoxSizer(wxHORIZONTAL);
    TopPanel->SetSizer(boxSizer241);
    
    SetName(wxT("GraphBaseClass"));
    SetMinClientSize(wxSize(400,300));
    SetSize(wxDLG_UNIT(this, wxSize(400,300)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
}

GraphBaseClass::~GraphBaseClass()
{
}

GridBaseClass::GridBaseClass(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    SetName(wxT("GridBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(400,300)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
}

GridBaseClass::~GridBaseClass()
{
}

ColorsBaseClass::ColorsBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    this->SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    SetBackgroundColour(wxColour(wxT("rgb(255,255,255)")));
    SetName(wxT("ColorsBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(ColorsBaseClass::OnClose), NULL, this);
    
}

ColorsBaseClass::~ColorsBaseClass()
{
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(ColorsBaseClass::OnClose), NULL, this);
    
}
